services:
  - type: web
    name: smm-telegram-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: SMM_API_URL
        value: https://bestfollows.com/api/v2
      - key: SMM_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_ADMIN_CHAT_ID
        sync: false
